name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
      - tex
  pull_request:
    branches:
      - main
      - master
      - tex

jobs:
  latex-test:
    name: Latex Test
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/mmore500/teximage:sha-77b8179
      options: --user root
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build LaTeX document
        run: |
          trap 'cat *.log || true >> "$GITHUB_OUTPUT"' EXIT
          make

  latex:
    name: Latex Build and Deploy
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    container:
      image: ghcr.io/mmore500/teximage:sha-77b8179
      options: --user root
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build LaTeX document
        run: |
          trap 'cat *.log || true >> "$GITHUB_OUTPUT"' EXIT
          make
      - name: Prepare deploy directory
        run: |
          mkdir -p deploy
          cp ${{ github.event.repository.name }}-draft.pdf deploy/
          echo '<html><body><a href="${{ github.event.repository.name }}-draft.pdf">Download Manuscript Draft [PDF]</a></body></html>' > deploy/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
